---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: "default-c4f76978.hcp.westeurope.azmk8s.io"
  KUBERNETES_SERVICE_PORT: "443"
